[target.x86_64-crustos]
runner = "./runner.sh"

[build]
target = "x86_64-crustos.json"
rustflags = ["-C", "code-model=kernel", "-C", "relocation-model=static", "-C", "link-arg=-Tlink.ld"]

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]
